#!/usr/bin/env node
/*
 * lock.js — encrypts the password-protected pages under /work.
 *
 * How the gate works
 *   /work/               one password field. Tries the password against every company
 *                        listed in work/manifest.json and opens the one that unlocks.
 *   /work/<company>/     a tiny shell page (index.html) that fetches locked.json and
 *                        decrypts it in the browser (PBKDF2 + AES-GCM via WebCrypto).
 *                        The password is remembered for the tab session only.
 *
 * Plaintext lives here and is NEVER committed (.gitignore):
 *   work/_src/passwords.json          { "ashby": "ashby-erika" }
 *   work/_src/<company>/index.html    the full page a company sees after the gate
 *
 * Generated and committed:
 *   work/<company>/locked.json        the encrypted page
 *   work/<company>/index.html         the shell (written once if missing, then left alone)
 *   work/manifest.json                the list of companies the gate tries
 *
 * Usage
 *   node scripts/lock.js              encrypt every company in passwords.json (skips unchanged pages)
 *   node scripts/lock.js --unlock     recover plaintext into work/_src from locked.json (needs the passwords)
 *   node scripts/lock.js --stage      same as default, then `git add` whatever it wrote (used by the hook)
 *
 * Automatic re-encrypt on commit: install the hook once per clone
 *   cp scripts/pre-commit .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
 * After that, editing work/_src/<company>/index.html and committing is all Erika has to do.
 *
 * Adding a company: add "<company>": "<password>" to passwords.json, create
 * work/_src/<company>/index.html, run this script (or just commit).
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { webcrypto, randomBytes } = require('crypto');
const subtle = webcrypto.subtle;

const ROOT = path.resolve(__dirname, '..');
const WORK = path.join(ROOT, 'work');
const SRC = path.join(WORK, '_src');
const PASSWORDS = path.join(SRC, 'passwords.json');
const ITERATIONS = 250000; // PBKDF2 rounds; ~0.2s per attempt in a browser

const args = new Set(process.argv.slice(2));
const quiet = args.has('--quiet');
const log = (...m) => { if (!quiet) console.log(...m); };

function readPasswords() {
    if (!fs.existsSync(PASSWORDS)) {
        console.error(`Missing ${path.relative(ROOT, PASSWORDS)} — create it as {"<company>": "<password>"}.`);
        process.exit(1);
    }
    return JSON.parse(fs.readFileSync(PASSWORDS, 'utf8'));
}

async function deriveKey(password, salt, usage) {
    const base = await subtle.importKey('raw', Buffer.from(password, 'utf8'), 'PBKDF2', false, ['deriveKey']);
    return subtle.deriveKey(
        { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
        base,
        { name: 'AES-GCM', length: 256 },
        false,
        [usage]
    );
}

async function encrypt(plaintext, password) {
    const salt = randomBytes(16);
    const iv = randomBytes(12);
    const key = await deriveKey(password, salt, 'encrypt');
    const ct = await subtle.encrypt({ name: 'AES-GCM', iv }, key, Buffer.from(plaintext, 'utf8'));
    return {
        v: 1,
        kdf: 'PBKDF2-SHA256',
        iter: ITERATIONS,
        salt: salt.toString('base64'),
        iv: iv.toString('base64'),
        ct: Buffer.from(ct).toString('base64')
    };
}

async function decrypt(payload, password) {
    try {
        const key = await deriveKey(password, Buffer.from(payload.salt, 'base64'), 'decrypt');
        const pt = await subtle.decrypt(
            { name: 'AES-GCM', iv: Buffer.from(payload.iv, 'base64') },
            key,
            Buffer.from(payload.ct, 'base64')
        );
        return Buffer.from(pt).toString('utf8');
    } catch (e) {
        return null;
    }
}

// The shell every company page uses. Same markup as work/index.html, page mode.
function shellHtml(company) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title>Erika Cary — Work</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@400;500;600&family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,700;12..96,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../work.css">
</head>
<body class="lock-body">
<!-- Generated by scripts/lock.js for "${company}". The real page is in locked.json and is decrypted in the browser. -->

<p class="lock-status" id="lock-status" hidden>Opening…</p>

<div class="lock" id="lock" hidden>
    <a class="lock-home" href="/">Erika Cary</a>
    <p class="lock-eyebrow">Selected work</p>
    <h1 class="lock-title">This work is shared by invitation.</h1>
    <p class="lock-sub">Enter the password from my application to open it.</p>
    <form class="lock-form" id="lock-form" autocomplete="off" novalidate>
        <label class="visually-hidden" for="lock-input">Password</label>
        <input class="lock-input" id="lock-input" type="password" placeholder="Password" autocomplete="current-password" required>
        <button class="btn btn-primary" id="lock-submit" type="submit">Open</button>
    </form>
    <p class="lock-error" id="lock-error" role="alert" aria-live="polite"></p>
</div>

<noscript><p class="lock-status">This page needs JavaScript to open.</p></noscript>

<script src="../locked.js"></script>
<script>ECLock.init({ mode: 'page', payload: 'locked.json' });</script>
</body>
</html>
`;
}

function gitAdd(files) {
    if (!files.length) return;
    execFileSync('git', ['add', '--', ...files], { cwd: ROOT, stdio: 'inherit' });
}

async function lock() {
    const passwords = readPasswords();
    const companies = Object.keys(passwords).sort();
    const written = [];

    for (const company of companies) {
        const srcFile = path.join(SRC, company, 'index.html');
        if (!fs.existsSync(srcFile)) {
            console.error(`Skipping "${company}": no ${path.relative(ROOT, srcFile)}.`);
            continue;
        }
        const plaintext = fs.readFileSync(srcFile, 'utf8');
        const outDir = path.join(WORK, company);
        const lockedFile = path.join(outDir, 'locked.json');
        const shellFile = path.join(outDir, 'index.html');
        fs.mkdirSync(outDir, { recursive: true });

        // Skip when the committed payload already decrypts to the same page, so the
        // pre-commit hook doesn't churn a fresh salt/iv into every commit.
        if (fs.existsSync(lockedFile)) {
            const existing = JSON.parse(fs.readFileSync(lockedFile, 'utf8'));
            if ((await decrypt(existing, passwords[company])) === plaintext) {
                log(`${company}: unchanged`);
                if (!fs.existsSync(shellFile)) { fs.writeFileSync(shellFile, shellHtml(company)); written.push(shellFile); }
                continue;
            }
        }

        const payload = await encrypt(plaintext, passwords[company]);
        fs.writeFileSync(lockedFile, JSON.stringify(payload) + '\n');
        written.push(lockedFile);
        if (!fs.existsSync(shellFile)) { fs.writeFileSync(shellFile, shellHtml(company)); written.push(shellFile); }
        log(`${company}: encrypted ${plaintext.length} chars -> ${path.relative(ROOT, lockedFile)}`);
    }

    const manifestFile = path.join(WORK, 'manifest.json');
    const manifest = JSON.stringify({ companies: companies.filter(c => fs.existsSync(path.join(WORK, c, 'locked.json'))) }, null, 2) + '\n';
    if (!fs.existsSync(manifestFile) || fs.readFileSync(manifestFile, 'utf8') !== manifest) {
        fs.writeFileSync(manifestFile, manifest);
        written.push(manifestFile);
    }

    if (args.has('--stage')) gitAdd(written.map(f => path.relative(ROOT, f)));
    return written;
}

async function unlock() {
    const passwords = readPasswords();
    for (const company of Object.keys(passwords)) {
        const lockedFile = path.join(WORK, company, 'locked.json');
        if (!fs.existsSync(lockedFile)) { console.error(`${company}: no locked.json`); continue; }
        const plaintext = await decrypt(JSON.parse(fs.readFileSync(lockedFile, 'utf8')), passwords[company]);
        if (plaintext === null) { console.error(`${company}: wrong password`); continue; }
        const srcFile = path.join(SRC, company, 'index.html');
        if (fs.existsSync(srcFile) && !args.has('--force')) { log(`${company}: ${path.relative(ROOT, srcFile)} exists, use --force to overwrite`); continue; }
        fs.mkdirSync(path.dirname(srcFile), { recursive: true });
        fs.writeFileSync(srcFile, plaintext);
        log(`${company}: recovered -> ${path.relative(ROOT, srcFile)}`);
    }
}

(args.has('--unlock') ? unlock() : lock()).catch(err => { console.error(err); process.exit(1); });
